services:
  vacation-rental-property-api:
    container_name: vacation-rental-property-api
    image: stivenramireza/vacation-rental-property-api:0.1.0
    ports:
      - ${PORT}:${PORT}
    networks:
      - vacation-rental-property
    environment:
      PORT: ${PORT}
      ENV: ${ENV}
      HOST: ${HOST}
      API_VERSION: ${API_VERSION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  vacation-rental-property:
