services:
  vacation-rental-property-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vacation-rental-property-api
    ports:
      - ${PORT}:${PORT} # App port
      - 9229:9229 # Debug port
    networks:
      - vacation-rental-property
    volumes:
      - .:/app
    depends_on:
      - postgres-db
    env_file:
      - .env
    environment:
      DB_HOST: postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:16.0
    ports:
      - ${DB_PORT}:5432
    networks:
      - vacation-rental-property
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  vacation-rental-property:

volumes:
  postgres-db-data:
